### ISSUE TITLE
has singleuser-base been updated?

### ISSUE THREAD

**Issue by mnfienen** [CUAHSI/ndst#2]
Hi @Castronova 

I'm using `FROM cuahsi/singleuser-base:2021.01.13` in my dockerfile and it's failing on build at `executor failed running [/bin/bash -o pipefail -c apt-get update &&     rm -rf /var/lib/apt/lists/*]: exit code: 100`

here's the error:
`#6 26.73 Reading package lists...`
`#6 27.56 E: The repository 'https://packages.irods.org/apt xenial Release' no longer has a Release file.`
Makes me wonder if maybe that base image is out-of-date.

**Comment by Castronova** [comment]
@mnfienen I'll take a look at this.

**Comment by Castronova** [comment]
@mnfienen I updated the base image and swapped `conda` with `mamba` to speed up build times. I also created a GitHub Action that will automatically build and push the image to DockerHub whenever we create a new release.
